#!/usr/bin/perl -w

open F, '<', 'tlog' or die "Can't open tlog: $!\n";
my %th;
while (sysread(F, $_, 16) == 16)
{
    my ($tid, $act, $data) = unpack 'VVQ';
    my $col = $th{$tid};
    $col=$th{$tid}=sprintf("\e[38;5;%dm",17+int rand(215)) unless defined $col;
    printf "%s%08x %08x %016x\e[0m\n", $col, $tid, $act, $data;
}
